DEBUG 2015-03-05 21:38:03,369: 	 Executing command: 'status'
DEBUG 2015-03-05 21:38:03,370: 	 Found /users/ec6821/.crab3 file
DEBUG 2015-03-05 21:38:03,381: 	 Checking credentials
DEBUG 2015-03-05 21:38:03,381: 	 Found proxy file /tmp/x509up_u32382
DEBUG 2015-03-05 21:38:03,381: 	 Getting proxy life time left
DEBUG 2015-03-05 21:38:03,885: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u32382 -timeleft
 output : 57337

 error: 
 retcode : 0
DEBUG 2015-03-05 21:38:04,390: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u32382 -actimeleft
 output : 57336

 error: 
 retcode : 0
DEBUG 2015-03-05 21:38:04,391: 	 Proxy valid for 15:55:37 hours
ERROR 2015-03-05 21:38:04,391: 	 Working directory for task crab_GJets_100to200_PU20bx25 not found 
ERROR 2015-03-05 21:38:04,391: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14/bin/crab", line 181, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14/bin/crab", line 166, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 288, in __init__
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14/lib/python2.6/site-packages/CRABClient/Commands/SubCommand.py", line 397, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/crabclient/3.3.14/lib/python2.6/site-packages/CRABClient/ClientUtilities.py", line 382, in loadCache
    raise TaskNotFoundException(msg)
TaskNotFoundException: Working directory for task crab_GJets_100to200_PU20bx25 not found 
